### ISSUE TITLE
Add button in the Feedly interface

### ISSUE THREAD

**Issue by Keith94** [splattael/firefox-feedly-tabs#1]
I'd prefer to have the Feedly tabs button directly on the feedly.com website, for example next to the "Refresh" button. Can your add-on or other scripts do this? This is to avoid cluttering the Firefox UI with too many buttons.

**Comment by splattael** [comment]
I like this idea and try to make it optional soonish :-)

**Comment by Keith94** [comment]
Any updates for this?

**Comment by splattael** [comment]
@Keith94 Long time no see ;) Sorry for the delay!

Sadly, I am quite busy right now. But I am keen to see this feature added. Any chance you could try it and submit a PR? :grinning: :purple_heart:

**Comment by Keith94** [comment]
I don't know how to do that...
Plus, the add-on will stop working in Firefox 57 if not converted to WebExtensions API.

Should I close this?

**Comment by splattael** [comment]
@Keith94 Oh, I was not aware of FireFox 57 changes. Interesting.

Please leave this issue open.

**Comment by splattael** [comment]
@Keith94

FYI, I've added a green button named "TABS" to feedly.com in the [Chrome version of this extension](github.com/splattael/chrome-feedly-tabs):

![screenshot from 2017-08-11 17-19-09](https://user-images.githubusercontent.com/28908/29219777-59f0dc4e-7eb9-11e7-90c7-23d4c20a0f3a.png)

WDYT?

**Comment by Keith94** [comment]
Yes. I like the look of it. :) Couple questions:

Can we configure it to open *unread* items only? As well as mark them as read after opening?

**Comment by splattael** [comment]
@Keith94 Good questions!

Currently, "Feedly tabs" is very opinionated has no configuration at all. It is only to open unread articles.
TBH, I'd like to avoid configuration as much as possible unless users (you :sunglasses:) really want it.

I thought about marking articles as read after opening. I'd like to mark each articles as read after the tab has been closed. WDYT?

**Comment by Keith94** [comment]
Well, if it's useful I may ask about an "unread only" option later (I think the Chrome ext. opens all articles currently?)

>mark each articles as read after the tab has been closed.

Sounds good to me, I'd be willing to try it.
